Indrani Jewellers/Models/Loan.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace Indrani_Jewellers.Models
{
    public class Loan
    {
        [Key]
        public int? LID { get; set; }


        [StringLength(45)]
        public string? CID { get; set; }

        [Required]
        [StringLength(45)]
        [Display(Name = "Customer Name")]
        public string? CustomerName { get; set; }


        [StringLength(45)]
        [Display(Name = "Customer ID")]
        public string? CustomerID { get; set; }

        [StringLength(45)]
        public string? Contact { get; set; }

        [EmailAddress]
        public string? Email { get; set; }


        [StringLength(45)]
        [Display(Name = "Product Name")]
        public string? Metal { get; set; }


        [Display(Name = "Total Gold Weight")]
        public string? TotalGoldWeight { get; set; }



        [Display(Name = "Total Silver Weight")]
        public decimal? TotalSilverWeight { get; set; }


        [StringLength(45)]
        [Display(Name = "Gold Rate")]
        public string? GoldRate { get; set; }

        [StringLength(45)]
        [Display(Name = "Silver Rate")]
        public string? SilverRate { get; set; }


        [StringLength(45)]
        [Display(Name = "Loan Amount")]
        public string? LoanAmount { get; set; }


        [Display(Name = "From Date")]
        [DataType(DataType.DateTime)]
        public DateTime? FromDate { get; set; }


        [Display(Name = "To Date")]
        [DataType(DataType.DateTime)]
        public DateTime? ToDate { get; set; }


        [StringLength(45)]
        [Display(Name = "Interest Per Annum")]
        public string IntrestPerMonth { get; set; }


        [StringLength(45)]
        [Display(Name = "Total Duration")]
        public string? TotalDuration { get; set; }

        [StringLength(45)]
        [Display(Name = "Is Active")]
        public int? IsActive { get; set; }


        [StringLength(45)]
        [Display(Name = "Is Archived")]
        public int? IsArchived { get; set; }


        [StringLength(45)]
        [Display(Name = "Created By")]
        public string? CreatedBy { get; set; }


        [Display(Name = "Created On")]
        [DataType(DataType.DateTime)]
        public DateTime? CreatedOn { get; set; }


        [Display(Name = "Modified By")]
        public int? ModifiedBy { get; set; }


        [Display(Name = "Modified On")]
        [DataType(DataType.DateTime)]
        public DateTime? ModifiedOn { get; set; }


        [StringLength(45)]
        [Display(Name = "Amount Given")]
        public string? AmountGiven { get; set; }


        [StringLength(45)]
        [Display(Name = "Amount Taken")]
        public string? AmountTaken { get; set; }


        [Display(Name = "Loan Date")]
        [DataType(DataType.DateTime)]
        public DateTime? LoanDate { get; set; }

        [Display(Name = "Loan Completed Date")]
        [DataType(DataType.DateTime)]
        public DateTime? LoanCompletedDate { get; set; }

        [ValidateNever]
        public List<LoanProductDetail> loanProductDetails { get; set; }
    }
}

Indrani Jewellers/Controllers/LoanController.cs
using Indrani_Jewellers.Data;
using Indrani_Jewellers.Models;
using Indrani_Jewellers.Services;
using Microsoft.AspNetCore.Mvc;

namespace Indrani_Jewellers.Controllers
{
    public class LoanController : BaseController
    {
        public readonly LoanService _loanServices;
        public readonly ApplicationDbContext _db;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly CustomerService _CustomerService;

        public LoanController(LoanService loanServices, ApplicationDbContext db, IHttpContextAccessor httpContextAccessor, CustomerService customerService)
        {
            _loanServices = loanServices;
            _db = db;
            _httpContextAccessor = httpContextAccessor;
            _CustomerService = customerService;
        }

        public IActionResult Index()
        {
            var loanList = _loanServices.GetLoanList();
            return View(loanList); ;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(Loan loan)
        {
            int Lid = _loanServices.InsertLoan(loan);

            foreach (var data in loan.loanProductDetails)
            {
                _loanServices.InsertLoanProducts(data, Lid);
            }

            return RedirectToAction(nameof(Index));
        }


        public IActionResult GetCustomerId(string cid)
        {
            var data = _db.customer_master.FirstOrDefault(m => m.CustomerID == cid);

            if (data == null)
            {
                return Json(null);
            }
            else
            {
                return Json(data);
            }
        }



        public IActionResult Details(int id)
        {
            // Fetch loan details
            var loan = _db.Loans.FirstOrDefault(m => m.LID == id);

            // Fetch loan product details
            var loanProducts = _loanServices.GetLoanProductList(id);

            if (loan == null)
            {
                return NotFound(); // Handle case where loan with the given ID is not found
            }

            // Assuming you have a view model to combine loan and loan product details
            var viewModel = new LoanDetailsViewModel
            {
                loan = loan,
                loanProductDetail = loanProducts
            };

            return View(viewModel); // Pass the view model to the view
        }


    }
}

Indrani Jewellers/Views/Loan/Details.cshtml
@model LoanDetailsViewModel

<div class="row">
    <div class="col-lg-12">
        <div class="card" id="loanForm">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header align-items-center d-flex">
                        <h4 class="card-title mb-0 flex-grow-1">Foreclousere Gold & Silver Loan</h4>
                    </div>
                    <br />
                    <div class="card-body">
                        <div class="live-preview">
                            <form method="post" asp-controller="Loan" asp-action="Create" class="row g-3 needs-validation" novalidate>
                                <div id="page1">
                                    <div class="row">
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label asp-for="loan.CustomerName" class="control-label"></label>
                                                <input asp-for="loan.CustomerName" class="form-control" id="cname" required />
                                                <span asp-validation-for="loan.CustomerName" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label asp-for="loan.Contact" class="control-label"></label>
                                                <input asp-for="loan.Contact" id="contact" class="form-control" required />
                                                <span asp-validation-for="loan.Contact" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label asp-for="loan.Email" class="control-label"></label>
                                                <input asp-for="loan.Email" id="email" type="email" class="form-control" required />
                                                <span asp-validation-for="loan.Email" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                   
                                </div>

                              

                
                                    <div class="row">
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label asp-for="loan.FromDate" class="control-label"></label>
                                                <input asp-for="loan.FromDate" type="datetime-local" class="form-control" id="fromDate" required />
                                                <span asp-validation-for="loan.FromDate" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label asp-for="loan.ToDate" class="control-label"></label>
                                                <input asp-for="loan.ToDate" type="datetime-local" class="form-control" id="toDate" required />
                                                <span asp-validation-for="loan.ToDate" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label asp-for="loan.IntrestPerMonth" class="control-label"></label>
                                                <input asp-for="loan.IntrestPerMonth" class="form-control" id="interestRate" required value="3%" readonly />
                                                <span asp-validation-for="loan.IntrestPerMonth" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label asp-for="loan.LoanAmount" class="control-label"></label>
                                                <input asp-for="loan.LoanAmount" class="form-control" id="loanAmount" required readonly />
                                                <span asp-validation-for="loan.LoanAmount" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label asp-for="loan.GoldRate" class="control-label"></label>
                                                <input asp-for="loan.GoldRate" class="form-control" id="goldRate" required value="7000" readonly />
                                                <span asp-validation-for="loan.GoldRate" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label asp-for="loan.SilverRate" class="control-label"></label>
                                                <input asp-for="loan.SilverRate" class="form-control" id="silverRate" required value="80" readonly />
                                                <span asp-validation-for="loan.SilverRate" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label asp-for="loan.TotalGoldWeight" class="control-label"></label>
                                                <input asp-for="loan.TotalGoldWeight" class="form-control" id="totalGoldWeight" required readonly />
                                                <span asp-validation-for="loan.TotalGoldWeight" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            <div class="mb-3">
                                                <label asp-for="loan.TotalSilverWeight" class="control-label"></label>
                                                <input asp-for="loan.TotalSilverWeight" class="form-control" id="totalSilverWeight" required readonly />
                                                <span asp-validation-for="loan.TotalSilverWeight" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                   
               
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end col-->
</div>

Indrani Jewellers/Views/Loan/Index.cshtml
@model IEnumerable<Indrani_Jewellers.Models.Loan>

<link href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/2.3.0/remixicon.css" rel="stylesheet">

@{
    ViewData["Title"] = "Index";
}

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0">Manage Employee</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Dashboards</a></li>
                    <li class="breadcrumb-item active">Employee</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<!-- start page title -->
<div class="row">
    <div class="col-lg-12">
        <div class="card" id="leadsList">
            <br />

            <!-- Search Button -->
            <div class="container">
                <div class="row justify-content-between mb-3">
                    <div class="col-md-3">
                        <input type="text" class="form-control" id="searchInput" placeholder="Search...">
                    </div>
                    <div class="col-md-3 text-md-right">
                        <a class="btn btn-warning btn-block btn-label waves-effect waves-light" asp-controller="Loan" asp-action="Create">
                           Apply Loan
                        </a>
                    </div>
                </div>
            </div>

            <!-- Disabled input -->
            <div class="card-body">
                <table id="productTable" class="display table table-bordered" style="width:100%">
                    <thead class="table-light">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.CustomerName)
                            </th>
                           
                            <th>
                                @Html.DisplayNameFor(model => model.Contact)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LoanAmount)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FromDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ToDate)
                            </th>
                            <th class="w-25">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CustomerName)
                                </td>
                           
                                <td>
                                    @Html.DisplayFor(modelItem => item.Contact)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LoanAmount)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FromDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ToDate)
                                </td>
                                <td>
                                    <ul class="list-inline hstack gap-2 mb-0">
                                        <li class="list-inline-item edit-item-btn">
                                            <a href="@Url.Action("Edit", new { id = item.LID })" class="btn btn-outline-warning btn-sm" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-placement="top" title="Edit">Edit</a>
                                        </li>
                                        <li class="list-inline-item view-item-btn">
                                            <a href="@Url.Action("Details", new { id = item.LID })" class="btn btn-outline-primary btn-sm" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-placement="top" title="View">View</a>
                                        </li>
                                        <li class="list-inline-item remove-item-btn">
                                            <a href="@Url.Action("Delete", new { id = item.LID })" class="btn btn-outline-danger btn-sm" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-placement="top" title="Delete">Delete</a>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- Search Button -->
        </div>
    </div>
</div>

<script src="~/assets/libs/sweetalert2/sweetalert2.all.min.js"></script>

<!-- Bootstrap and DataTables Scripts and Stylesheets -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap5.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap5.min.js"></script>

<!-- DataTable Initialization -->
<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

@if (TempData["success"] != null)
{
    <script>
        debugger;
        var successMessage = '@TempData["success"]';
        var isSuccess = '@TempData["Valid"]' === "1";

        Swal.fire({
            icon: isSuccess ? 'success' : 'error',
            title: successMessage,
            showConfirmButton: false,
            timer: 3000
        });
    </script>
}

<script>
    document.getElementById("searchInput").addEventListener("input", function () {
        var input = this.value.trim().toLowerCase();
        var rows = document.querySelectorAll("#productTable tbody tr");

        rows.forEach(function (row) {
            var text = row.innerText.toLowerCase();
            row.style.display = text.includes(input) ? "" : "none";
        });
    });
</script>