Indrani Jewellers/Models/Loan.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace Indrani_Jewellers.Models
{
    public class Loan
    {
        [Key]
        public int? LID { get; set; }


        [StringLength(45)]
        public string? CID { get; set; }

        [Required]
        [StringLength(45)]
        [Display(Name = "Customer Name")]
        public string? CustomerName { get; set; }


        [StringLength(45)]
        [Display(Name = "Customer ID")]
        public string? CustomerID { get; set; }

        [StringLength(45)]
        public string? Contact { get; set; }

        [EmailAddress]
        public string? Email { get; set; }


        [StringLength(45)]
        [Display(Name = "Product Name")]
        public string? Metal { get; set; }


        [Display(Name = "Total Gold Weight")]
        public string? TotalGoldWeight { get; set; }



        [Display(Name = "Total Silver Weight")]
        public decimal? TotalSilverWeight { get; set; }


        [StringLength(45)]
        [Display(Name = "Gold Rate")]
        public string? GoldRate { get; set; }

        [StringLength(45)]
        [Display(Name = "Silver Rate")]
        public string? SilverRate { get; set; }


        [StringLength(45)]
        [Display(Name = "Loan Amount")]
        public string? LoanAmount { get; set; }


        [Display(Name = "From Date")]
        [DataType(DataType.DateTime)]
        public DateTime? FromDate { get; set; }


        [Display(Name = "To Date")]
        [DataType(DataType.DateTime)]
        public DateTime? ToDate { get; set; }


        [StringLength(45)]
        [Display(Name = "Interest Per Annum")]
        public string IntrestPerMonth { get; set; }


        [StringLength(45)]
        [Display(Name = "Total Duration")]
        public string? TotalDuration { get; set; }

        [StringLength(45)]
        [Display(Name = "Is Active")]
        public int? IsActive { get; set; }


        [StringLength(45)]
        [Display(Name = "Is Archived")]
        public int? IsArchived { get; set; }


        [StringLength(45)]
        [Display(Name = "Created By")]
        public string? CreatedBy { get; set; }


        [Display(Name = "Created On")]
        [DataType(DataType.DateTime)]
        public DateTime? CreatedOn { get; set; }


        [Display(Name = "Modified By")]
        public int? ModifiedBy { get; set; }


        [Display(Name = "Modified On")]
        [DataType(DataType.DateTime)]
        public DateTime? ModifiedOn { get; set; }


        [StringLength(45)]
        [Display(Name = "Amount Given")]
        public string? AmountGiven { get; set; }


        [StringLength(45)]
        [Display(Name = "Amount Taken")]
        public string? AmountTaken { get; set; }


        [Display(Name = "Loan Date")]
        [DataType(DataType.DateTime)]
        public DateTime? LoanDate { get; set; }

        [Display(Name = "Loan Completed Date")]
        [DataType(DataType.DateTime)]
        public DateTime? LoanCompletedDate { get; set; }

        [ValidateNever]
        public List<LoanProductDetail> loanProductDetails { get; set; }
    }
}

Indrani Jewellers/Controllers/LandingPageController.cs
using Indrani_Jewellers.Data;
using Indrani_Jewellers.Models;
using Indrani_Jewellers.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Indrani_Jewellers.Controllers
{
    public class LandingPageController : Controller
    {
        public readonly LoanService _loanServices;
        public readonly ApplicationDbContext _db;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ProductSeriveces _productServices;
        private readonly ILogger<LandingPageController> _logger;

        public LandingPageController(ILogger<LandingPageController> logger, ProductSeriveces productServices, LoanService loanServices, ApplicationDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _loanServices = loanServices;
            _db = db;
            _httpContextAccessor = httpContextAccessor;
            _productServices = productServices;
            _logger = logger;
        }
        public IActionResult Index()
        {
            var productList = _productServices.GetProductMasterList();
            return View(productList);
        }

        public IActionResult Loan()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Loan(string c)
        {
            var user = _db.Loans.FirstOrDefault(m => m.CustomerID == c);

            if (user != null)
            {
                return Json(false);
            }
            return Json(true);

        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var data = _db.product_master.FirstOrDefault(m => m.productId == id);
            if (data == null)
            {
                return RedirectToAction("Index");
            }


            return View(data);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Details(ProductMasterModel pm)
        {
            return View();
        }
    }
}

Indrani Jewellers/Controllers/LoanController.cs
using Indrani_Jewellers.Data;
using Indrani_Jewellers.Models;
using Indrani_Jewellers.Services;
using Microsoft.AspNetCore.Mvc;

namespace Indrani_Jewellers.Controllers
{
    public class LoanController : BaseController
    {
        public readonly LoanService _loanServices;
        public readonly ApplicationDbContext _db;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly CustomerService _CustomerService;

        public LoanController(LoanService loanServices, ApplicationDbContext db, IHttpContextAccessor httpContextAccessor, CustomerService customerService)
        {
            _loanServices = loanServices;
            _db = db;
            _httpContextAccessor = httpContextAccessor;
            _CustomerService = customerService;
        }

        public IActionResult Index()
        {
            var loanList = _loanServices.GetLoanList();
            return View(loanList); ;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(Loan loan)
        {
            int Lid = _loanServices.InsertLoan(loan);

            foreach (var data in loan.loanProductDetails)
            {
                _loanServices.InsertLoanProducts(data, Lid);
            }

            return RedirectToAction(nameof(Index));
        }


        public IActionResult GetCustomerId(string cid)
        {
            var data = _db.customer_master.FirstOrDefault(m => m.CustomerID == cid);

            if (data == null)
            {
                return Json(null);
            }
            else
            {
                return Json(data);
            }
        }



        public IActionResult Details(int id)
        {
            // Fetch loan details
            var loan = _db.Loans.FirstOrDefault(m => m.LID == id);

            // Fetch loan product details
            var loanProducts = _loanServices.GetLoanProductList(id);

            if (loan == null)
            {
                return NotFound(); // Handle case where loan with the given ID is not found
            }

            // Assuming you have a view model to combine loan and loan product details
            var viewModel = new LoanDetailsViewModel
            {
                loan = loan,
                loanProductDetail = loanProducts
            };

            return View(viewModel); // Pass the view model to the view
        }


    }
}

Indrani Jewellers/Views/LandingPage/Details.cshtml
@model Indrani_Jewellers.Models.ProductMasterModel
@{
    Layout = null;
}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="header bg-white border-bottom shadow-sm py-3 fixed-top">
    <div class="container d-flex justify-content-between align-items-center">
        <a href="/LandingPage/Index" class="logo">
            <img src="~/assets/images/lplogo.jpg" alt="Jewellery Store" class="header-img img-fluid" style="max-width: 150px;">
        </a>
        <ul class="nav">
            <li class="nav-item"><a href="#" class="nav-link text-dark">Diamond</a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark">Gold</a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark">Platinum</a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark">Silver</a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark">Coins</a></li>
        </ul>
        <ul class="nav">
            <li class="nav-item"><a asp-controller="LandingPage" asp-action="Loan" class="nav-link text-dark">Apply for Gold & Silver Loan</a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark"></a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark"></a></li>
            <li class="nav-item"><a asp-controller="Account" asp-action="Login" class="nav-link text-dark">Login</a></li>
        </ul>
    </div>
</div>

<div class="container mt-5 pt-5">
    <form method="post">
        <input type="hidden" asp-for="productId" />
        <div class="card shadow border-0 mt-4 mb-4">
            <div class="card-header bg-secondary bg-gradient text-light py-4">
                <div class="row">
                    <div class="col-12 text-center">
                        <h3 class="text-white text-uppercase">@Model.productName</h3>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="py-3">
                    <div class="row mb-3">
                        <div class="col-12 col-md-6 col-lg-4 offset-lg-1 text-center mb-3">
                            <img src="@Model.ImageUrl" alt="@Model.productName" class="img-fluid rounded" />
                        </div>
                        <div class="col-12 col-md-6 col-lg-6">
                            <div class="row mb-3">
                                <div class="col-6 col-lg-3 bg-white border-bottom">
                                    <div class="text-dark text-opacity-50 fw-semibold">Weight</div>
                                    <div class="text-dark">@Model.gms gms</div>
                                </div>
                                <div class="col-6 col-lg-3 bg-white border-bottom">
                                    <div class="text-dark text-opacity-50 fw-semibold">Quantity</div>
                                    <div class="text-dark">@Model.quantity</div>
                                </div>
                                <div class="col-6 col-lg-3 bg-white border-bottom">
                                    <div class="text-dark text-opacity-50 fw-semibold">Price</div>
                                    <div class="text-warning fw-bold">Price</div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-md-6 pb-1">
                                    <button type="submit" class="btn btn-primary bg-gradient w-100 py-2 text-uppercase fw-semibold">
                                        Add to Cart
                                    </button>
                                </div>
                                <div class="col-12 col-md-6 pb-1">
                                    <a asp-action="Index" class="btn btn-outline-primary bg-gradient w-100 py-2 text-uppercase fw-semibold">
                                        Back to Home
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

Indrani Jewellers/Views/LandingPage/Index.cshtml
@model IEnumerable<Indrani_Jewellers.Models.ProductMasterModel>

@{
    Layout = null;
}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="header bg-white border-bottom shadow-sm py-3 fixed-top">
    <div class="container d-flex justify-content-between align-items-center">
        <a href="/LandingPage/Index" class="logo">
            <img src="~/assets/images/lplogo.jpg"  alt="Jewellery Store" class="header-img img-fluid" style="max-width: 150px;">
        </a>
        <ul class="nav">
            <li class="nav-item"><a href="#" class="nav-link text-dark">Diamond</a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark">Gold</a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark">Platinum</a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark">Silver</a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark">Coins</a></li>
        </ul>
        <ul class="nav">
            <li class="nav-item"><a asp-controller="LandingPage" asp-action="Loan" class="nav-link text-dark">Apply for Gold & Silver Loan</a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark"></a></li>
            <li class="nav-item"><a href="#" class="nav-link text-dark"></a></li>
            <li class="nav-item"><a asp-controller="Account" asp-action="Login" class="nav-link text-dark">Login</a></li>
        </ul>
    </div>
</div>

<div class="container mt-5 pt-5">
    <div class="row">
        @foreach (var product in Model)
        {
            <div class="col-lg-3 col-sm-6 mb-4">
                <div class="card h-100 shadow-sm border-top border-5 rounded">
                    <img src="@Url.Content(product.ImageUrl.Replace('\\', '/'))" class="card-img-top rounded" alt="Product Image" />
                    <div class="card-body">
                        <h5 class="card-title text-center text-uppercase">@product.productName</h5>
                        <p class="text-center mb-0">Weight: <span class="text-decoration-line-through">@product.gms</span> Gm</p>
                    </div>
                    <div class="card-footer text-center">
                        <a asp-action="Details" asp-route-id="@product.productId" class="btn btn-primary w-100">Details</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>